In [1]:
import pandas as pd
import tkinter as tk
from tkinter import filedialog

In [2]:
root = tk.Tk()
root.withdraw()
print ('A abrir ficheiro...')
file = filedialog.askopenfilename(filetypes = [("EXCEL","*.xlsx")])

A abrir ficheiro...

In [3]:
df = pd.read_excel(file)

In [4]:
a = list(df.columns.values)

['m/z', '29 MeOH +', 'm/z.1', '30 MeOH +', 'm/z.2', '31 MeOH +']

In [5]:
t = df[[a[0], a[1]]]
t.insert(2, 'Tubo', a[1])
t.columns = ['Mass', 'Intensity', 'Tubo']
for x in range(2,len(a),2):
    tempdf = df[[a[x], a[x+1]]]
    tempdf.insert(2, 'Tubo', a[x+1])
    tempdf.columns = ['Mass', 'Intensity', 'Tubo']
    t = pd.concat([t,tempdf])

In [6]:
t = t.sort_values('Mass')
t = t.reset_index()
t = t.drop('index', axis=1)
t

          Mass  Intensity       Tubo
0     97.04496   105090.0  31 MeOH +
1     97.07279    95693.0  29 MeOH +
2     97.11142    95771.0  30 MeOH +
3     97.14361   117166.0  30 MeOH +
4     97.15448   101862.0  29 MeOH +
5     97.16289   108968.0  31 MeOH +
6     97.17749   166304.0  31 MeOH +
7     97.17755   146957.0  29 MeOH +
8     97.17761   141577.0  30 MeOH +
9     97.36901   106897.0  31 MeOH +
10    97.43958    98382.0  30 MeOH +
11    97.45119   105519.0  30 MeOH +
12    97.53003   104825.0  31 MeOH +
13    97.55250   102825.0  29 MeOH +
14    97.63142    99415.0  30 MeOH +
15    97.67036    96145.0  29 MeOH +
16    97.67143    97363.0  29 MeOH +
17    97.68034   105522.0  29 MeOH +
18    97.71084   105277.0  29 MeOH +
19    97.76366    99723.0  29 MeOH +
20    97.80040   100021.0  30 MeOH +
21    97.92005   100294.0  31 MeOH +
22    97.96593   110956.0  29 MeOH +
23    97.97977   101404.0  29 MeOH +
24    98.03892   107511.0  31 MeOH +
25    98.06548    95609.0  30 MeOH +
26    98.06978   102461.0  31 MeOH +
27    98.11532   104892.0  31 MeOH +
28    98.35143    95328.0  31 MeOH +
29    98.38647    95883.0  31 MeOH +
...        ...        ...        ...
4896       NaN        NaN  30 MeOH +
4897       NaN        NaN  30 MeOH +
4898       NaN        NaN  30 MeOH +
4899       NaN        NaN  30 MeOH +
4900       NaN        NaN  30 MeOH +
4901       NaN        NaN  30 MeOH +
4902       NaN        NaN  30 MeOH +
4903       NaN        NaN  30 MeOH +
4904       NaN        NaN  30 MeOH +
4905       NaN        NaN  30 MeOH +
4906       NaN        NaN  30 MeOH +
4907       NaN        NaN  30 MeOH +
4908       NaN        NaN  30 MeOH +
4909       NaN        NaN  30 MeOH +
4910       NaN        NaN  30 MeOH +
4911       NaN        NaN  30 MeOH +
4912       NaN        NaN  30 MeOH +
4913       NaN        NaN  30 MeOH +
4914       NaN        NaN  30 MeOH +
4915       NaN        NaN  31 MeOH +
4916       NaN        NaN  31 MeOH +
4917       NaN        NaN  31 MeOH +
4918       NaN        NaN  31 MeOH +
4919       NaN        NaN  31 MeOH +
4920       NaN        NaN  31 MeOH +
4921       NaN        NaN  31 MeOH +
4922       NaN        NaN  31 MeOH +
4923       NaN        NaN  31 MeOH +
4924       NaN        NaN  31 MeOH +
4925       NaN        NaN  31 MeOH +

[4926 rows x 3 columns]

In [7]:
dfp = pd.DataFrame()
mass = []
d = {}
last=0
error=1
for index, row in t.iterrows():
    if index == 0:
        last = row.Mass
        d[row.Tubo] = row.Intensity
        mass.append(row.Mass)        
        continue
    elif abs((last-row.Mass)*1000000)/last <= error:
        d[row.Tubo] = row.Intensity
        mass.append(row.Mass)
    else:
        c = sum(mass)/len(mass)
        df_temp = pd.DataFrame(d, index=[c])
        dfp = pd.concat([dfp,df_temp])
        mass = []
        d = {}
        last=row.Mass
        d[row.Tubo] = row.Intensity
        mass.append(row.Mass)
dfp = dfp[pd.notnull(dfp.index)]
dfp

           29 MeOH +  30 MeOH +  31 MeOH +
97.04496         NaN        NaN   105090.0
97.07279     95693.0        NaN        NaN
97.11142         NaN    95771.0        NaN
97.14361         NaN   117166.0        NaN
97.15448    101862.0        NaN        NaN
97.16289         NaN        NaN   108968.0
97.17752    146957.0        NaN   166304.0
97.17761         NaN   141577.0        NaN
97.36901         NaN        NaN   106897.0
97.43958         NaN    98382.0        NaN
97.45119         NaN   105519.0        NaN
97.53003         NaN        NaN   104825.0
97.55250    102825.0        NaN        NaN
97.63142         NaN    99415.0        NaN
97.67036     96145.0        NaN        NaN
97.67143     97363.0        NaN        NaN
97.68034    105522.0        NaN        NaN
97.71084    105277.0        NaN        NaN
97.76366     99723.0        NaN        NaN
97.80040         NaN   100021.0        NaN
97.92005         NaN        NaN   100294.0
97.96593    110956.0        NaN        NaN
97.97977    101404.0        NaN        NaN
98.03892         NaN        NaN   107511.0
98.06548         NaN    95609.0        NaN
98.06978         NaN        NaN   102461.0
98.11532         NaN        NaN   104892.0
98.35143         NaN        NaN    95328.0
98.38647         NaN        NaN    95883.0
98.42029         NaN        NaN   102673.0
...              ...        ...        ...
895.66177        NaN        NaN   125221.0
900.60243        NaN        NaN   119393.0
902.04352        NaN   119989.0        NaN
905.51690        NaN        NaN   133986.0
907.43171        NaN   124498.0        NaN
908.16950   117397.0        NaN        NaN
913.22911        NaN   127492.0        NaN
918.81087        NaN   127806.0        NaN
919.22825   113282.0        NaN        NaN
919.48043        NaN        NaN   121519.0
924.20056   112780.0        NaN        NaN
925.75849        NaN   128964.0        NaN
929.19372   113265.0        NaN        NaN
930.57228   114438.0        NaN        NaN
934.07261        NaN        NaN   116195.0
935.09177   114510.0        NaN        NaN
944.16224   133295.0        NaN        NaN
945.88636        NaN   119629.0        NaN
948.07962   117226.0        NaN        NaN
953.07987        NaN        NaN   117556.0
957.21275        NaN        NaN   127856.0
963.40494        NaN   137121.0        NaN
972.51353        NaN        NaN   122592.0
973.82392        NaN        NaN   137790.0
973.93206        NaN   123483.0        NaN
975.37147   127231.0        NaN        NaN
985.30528   115713.0        NaN        NaN
986.37036        NaN        NaN   115775.0
987.85857   116902.0        NaN        NaN
988.54888        NaN        NaN   120981.0

[3734 rows x 3 columns]

In [8]:
dfp.insert(len(dfp.columns), 'Réplicas', dfp.notnull().sum(axis=1))
dfp

           29 MeOH +  30 MeOH +  31 MeOH +  Réplicas
97.04496         NaN        NaN   105090.0         1
97.07279     95693.0        NaN        NaN         1
97.11142         NaN    95771.0        NaN         1
97.14361         NaN   117166.0        NaN         1
97.15448    101862.0        NaN        NaN         1
97.16289         NaN        NaN   108968.0         1
97.17752    146957.0        NaN   166304.0         2
97.17761         NaN   141577.0        NaN         1
97.36901         NaN        NaN   106897.0         1
97.43958         NaN    98382.0        NaN         1
97.45119         NaN   105519.0        NaN         1
97.53003         NaN        NaN   104825.0         1
97.55250    102825.0        NaN        NaN         1
97.63142         NaN    99415.0        NaN         1
97.67036     96145.0        NaN        NaN         1
97.67143     97363.0        NaN        NaN         1
97.68034    105522.0        NaN        NaN         1
97.71084    105277.0        NaN        NaN         1
97.76366     99723.0        NaN        NaN         1
97.80040         NaN   100021.0        NaN         1
97.92005         NaN        NaN   100294.0         1
97.96593    110956.0        NaN        NaN         1
97.97977    101404.0        NaN        NaN         1
98.03892         NaN        NaN   107511.0         1
98.06548         NaN    95609.0        NaN         1
98.06978         NaN        NaN   102461.0         1
98.11532         NaN        NaN   104892.0         1
98.35143         NaN        NaN    95328.0         1
98.38647         NaN        NaN    95883.0         1
98.42029         NaN        NaN   102673.0         1
...              ...        ...        ...       ...
895.66177        NaN        NaN   125221.0         1
900.60243        NaN        NaN   119393.0         1
902.04352        NaN   119989.0        NaN         1
905.51690        NaN        NaN   133986.0         1
907.43171        NaN   124498.0        NaN         1
908.16950   117397.0        NaN        NaN         1
913.22911        NaN   127492.0        NaN         1
918.81087        NaN   127806.0        NaN         1
919.22825   113282.0        NaN        NaN         1
919.48043        NaN        NaN   121519.0         1
924.20056   112780.0        NaN        NaN         1
925.75849        NaN   128964.0        NaN         1
929.19372   113265.0        NaN        NaN         1
930.57228   114438.0        NaN        NaN         1
934.07261        NaN        NaN   116195.0         1
935.09177   114510.0        NaN        NaN         1
944.16224   133295.0        NaN        NaN         1
945.88636        NaN   119629.0        NaN         1
948.07962   117226.0        NaN        NaN         1
953.07987        NaN        NaN   117556.0         1
957.21275        NaN        NaN   127856.0         1
963.40494        NaN   137121.0        NaN         1
972.51353        NaN        NaN   122592.0         1
973.82392        NaN        NaN   137790.0         1
973.93206        NaN   123483.0        NaN         1
975.37147   127231.0        NaN        NaN         1
985.30528   115713.0        NaN        NaN         1
986.37036        NaN        NaN   115775.0         1
987.85857   116902.0        NaN        NaN         1
988.54888        NaN        NaN   120981.0         1

[3734 rows x 4 columns]

In [9]:
dfp.to_excel(file[:-5]+'_aligned.xlsx', index=True, header=True, index_label='m/z', sheet_name=file.split('/')[-1].split('.xlsx')[0])